//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVirtual.Models
{
    using System;
    
    public partial class ObterPromocoes_Result1
    {
        public string nomeKit { get; set; }
        public short qtd { get; set; }
        public decimal preco { get; set; }
        public string promocao { get; set; }
        public Nullable<decimal> economia { get; set; }
        public int codProduto { get; set; }
        public int codPromocao { get; set; }
    }
}
